# -*- coding: utf-8 -*-
"""a2_p1_Shah_116727594.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1loIcnbdwtdSW7XEJGMWy0uHTN63oxXF4
"""

from transformers import RobertaTokenizerFast

# Initialize RoBERTa Tokenizer
tokenizer = RobertaTokenizerFast.from_pretrained("roberta-base")

# Example: Tokenizing a sentence
text = "When did SBU open?"
tokens = tokenizer.encode(text, add_special_tokens=True)
decoded_text = tokenizer.convert_ids_to_tokens(tokens)

# Print results
print("Tokenized IDs:", tokens)
print("Decoded Tokens:", decoded_text)
print("BOS Token:", tokenizer.bos_token)
print("EOS Token:", tokenizer.eos_token)
print("Pad Token:", tokenizer.pad_token)

from google.colab import files
uploaded = files.upload()

import csv

# Read the CSV file
with open('songs.csv', newline='', encoding='utf-8') as f:
    reader = csv.reader(f)
    data = list(reader)[1:-5]  # Remove header and last 5 rows


lyrics_data = [row[2] for row in data]



first_tokens = tokenizer.tokenize(lyrics_data[0])
last_tokens = tokenizer.tokenize(lyrics_data[-1])

# Print Checkpoint output
print("\nCheckpoint 1.1:")
print("First:", first_tokens)
print("Last:", last_tokens)

import csv
import collections
import math
from transformers import RobertaTokenizerFast

class TrigramLM:
    def __init__(self, tokenizer):
        self.tokenizer = tokenizer
        self.unigram_counts = collections.defaultdict(int)
        self.bigram_counts = collections.defaultdict(int)
        self.trigram_counts = collections.defaultdict(int)
        self.vocab = set()
        self.total_unigrams = 0
        self.OOV = "<OOV>"  # Out-of-vocabulary token

    def train(self, datasets):
        """Compute smoothed unigram, bigram, and trigram probabilities."""
        for song in datasets:
            tokens = [self.tokenizer.bos_token] + self.tokenizer.tokenize(song) + [self.tokenizer.eos_token]
            self.vocab.update(tokens)

            for i in range(len(tokens)):
                self.unigram_counts[tokens[i]] += 1
                self.total_unigrams += 1

                if i > 0:
                    self.bigram_counts[(tokens[i-1], tokens[i])] += 1

                if i > 1:
                    self.trigram_counts[(tokens[i-2], tokens[i-1], tokens[i])] += 1

        # Add OOV token to vocabulary
        self.vocab.add(self.OOV)

    def nextProb(self, history_toks, next_toks):
        """Return probabilities of next tokens given history tokens using trigram model."""
        if len(history_toks) >= 2:
            history = tuple(history_toks[-2:])
        else:
            history = tuple(history_toks)  # Use available context

        probabilities = {}

        for next_tok in next_toks:
            trigram = history + (next_tok,)
            bigram = history
            unigram = next_tok

            # Apply add-one smoothing
            trigram_prob = (self.trigram_counts[trigram] + 1) / (self.bigram_counts[bigram] + len(self.vocab))
            bigram_prob = (self.bigram_counts[bigram] + 1) / (self.unigram_counts.get(history[-1], 1) + len(self.vocab))
            unigram_prob = (self.unigram_counts[unigram] + 1) / (self.total_unigrams + len(self.vocab))

            # Combine probabilities (backoff model)
            probabilities[next_tok] = 0.6 * trigram_prob + 0.3 * bigram_prob + 0.1 * unigram_prob

        return probabilities

# Load RoBERTa Tokenizer
# tokenizer = RobertaTokenizerFast.from_pretrained("roberta-base")

# Read dataset
with open('songs.csv', newline='', encoding='utf-8') as f:
    reader = csv.reader(f)
    data = list(reader)[1:-5]  # Remove header and last 5 rows

# Extract lyrics column (Assuming column index 1)
lyrics_data = [row[2] for row in data]

# Initialize and train LM
lm = TrigramLM(tokenizer)
lm.train(lyrics_data)

# Compute next token probabilities
history_toks_1 = ["<s>", "Are", "Ġwe"]
next_toks_1 = ["Gout", "Ġin", "Ġto", "Ġpretending", "Ġonly"]

history_toks_2 = ["And", "Ġit"]
next_toks_2 = ["Ġwas", "m", "Ġstood", "Ġknow", "Ġscream", "Ġpromise"]

print("\nCheckpoint 1.2:")
print("Next token probabilities for first history:", lm.nextProb(history_toks_1, next_toks_1))
print("Next token probabilities for second history:", lm.nextProb(history_toks_2, next_toks_2))

import math

def get_perplexity(probs):
    """
    Compute the perplexity given a list of token probabilities.

    :param probs: List of probabilities for each token in a sequence.
    :return: Perplexity score (float)
    """
    if not probs or any(p == 0 for p in probs):
        return float('inf')  # Avoid log(0) errors

    log_sum = sum(math.log(p) for p in probs)  # Sum of log probabilities
    N = len(probs)  # Number of tokens

    perplexity = math.exp(-log_sum / N)  # Compute perplexity
    return perplexity

# Example test cases from Checkpoint 1.3
test_cases = [
    ['And', 'Ġyou', 'Ġgotta', 'Ġlive', 'Ġwith', 'Ġthe', 'Ġbad', 'Ġblood', 'Ġnow'],
    ['Sit', 'Ġquiet', 'Ġby', 'Ġmy', 'Ġside', 'Ġin', 'Ġthe', 'Ġshade'],
    ['And', 'ĠI', 'm', 'Ġnot', 'Ġeven', 'Ġsorry', ',', 'Ġnights', 'Ġare', 'Ġso', 'Ġstarry'],
    ['You', 'Ġmake', 'Ġme', 'Ġcrazy', ',', 'Ġcrazy', ',', 'Ġcrazy'],
    ['When', 'Ġtime', 'Ġstood', 'Ġstill', ',', 'ĠI', 'Ġhad', 'Ġyou']
]

# Compute perplexity for each test case
for i, test_case in enumerate(test_cases, 1):
    probs = []
    history = ["<s>"]  # Start with BOS token

    for token in test_case:
        next_prob = lm.nextProb(history, [token])  # Get token probability
        probs.append(next_prob.get(token, 1e-10))  # Avoid log(0) errors
        history.append(token)  # Update history

    perplexity = get_perplexity(probs)
    print(f"Checkpoint 1.3 - Perplexity for case {i}: {perplexity}")





