# -*- coding: utf-8 -*-
"""a2_p2_Shah_116727594.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qtyMpGw26nXZWpSvLaTzPfvN5Pw7eivp
"""

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

import torch
from torch import nn
import torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader
import csv
import re
from transformers import GPT2TokenizerFast
import matplotlib.pyplot as plt
import sys

# Initialize tokenizer
tokenizer = GPT2TokenizerFast.from_pretrained('gpt2')
tokenizer.pad_token = tokenizer.eos_token  # Set pad token to EOS token
tokenizer.bos_token = '<s>'
tokenizer.eos_token = '</s>'

# Checkpoint 2.1: Preparing the Dataset
def chunk_tokens(tokens, start_token_id, end_token_id, pad_token_id, chunk_len=128):
    effective_chunk_len = chunk_len - 2  # Account for BOS and EOS
    chunks = []
    for i in range(0, len(tokens), effective_chunk_len):
        chunk = tokens[i:i + effective_chunk_len]
        chunk = [start_token_id] + chunk + [end_token_id]
        if len(chunk) < chunk_len:
            chunk += [pad_token_id] * (chunk_len - len(chunk))
        chunks.append(chunk)
    return torch.tensor(chunks)

# Load and process dataset
with open('songs.csv', newline='') as f:
    reader = csv.reader(f)
    data = list(reader)[1:-5]  # Exclude header and last 5 songs

chunk_len = 64
all_chunks = []

for row in data:
    lyrics = row[2]  # Lyrics is the third column
    # Remove section markers
    lyrics = re.sub(r'\n\[[\x20-\x7f]+\]', '', lyrics)
    tokens = tokenizer.encode(lyrics)
    chunks = chunk_tokens(tokens, tokenizer.bos_token_id, tokenizer.eos_token_id, tokenizer.pad_token_id, chunk_len)
    all_chunks.append(chunks)

# Stack all chunks into a single tensor
all_chunks = torch.cat(all_chunks, dim=0)
X = all_chunks[:, :-1]  # All but last token
y = all_chunks[:, 1:]   # All but first token

# Create dataset and dataloader
dataset = TensorDataset(X, y)
dataloader = DataLoader(dataset, batch_size=32, drop_last=True)

# Checkpoint 2.1 Output: Find "Enchanted (Taylor's Version)"
print("\nCheckpoint 2.1:")
output_file = "a2_p2_Shah_116727594_OUTPUT.txt"
with open(output_file, "w", encoding="utf8") as outfile:
    outfile.write("Checkpoint 2.1: \n")
    for i, row in enumerate(data):
        title, album = row[0], row[1]
        if title == "Enchanted (Taylor's Version)" and album == "Speak Now (Taylor's Version)":
            lyrics = row[2]
            lyrics = re.sub(r'\n\[[\x20-\x7f]+\]', '', lyrics)
            tokens = tokenizer.encode(lyrics)
            enchanted_chunks = chunk_tokens(tokens, tokenizer.bos_token_id, tokenizer.eos_token_id, tokenizer.pad_token_id, chunk_len)
            print(f"Chunked tensors for 'Enchanted (Taylor's Version)':\n{enchanted_chunks}")
            outfile.write(f"Chunked tensors for 'Enchanted (Taylor's Version)':\n{enchanted_chunks}\n")
            break

import torch.nn.functional as F

def get_probs(model, tokenizer, text, device):
    model.eval()
    tokens = tokenizer.encode(text, return_tensors="pt").to(device)

    with torch.no_grad():
        logits, _ = model(tokens)  # Get logits from model

    probs = F.softmax(logits, dim=-1)  # Apply softmax to get probabilities
    return probs

import math

def get_perplexity(probs):
    """
    Compute the perplexity given a list of token probabilities.

    :param probs: List of probabilities for each token in a sequence.
    :return: Perplexity score (float)
    """
    if not probs or any(p == 0 for p in probs):
        return float('inf')  # Avoid log(0) errors

    log_sum = sum(math.log(p) for p in probs)  # Sum of log probabilities
    N = len(probs)  # Number of tokens

    perplexity = math.exp(-log_sum / N)  # Compute perplexity
    return perplexity

# Checkpoint 2.2: RecurrentLM Definition
class RecurrentLM(nn.Module):
    def __init__(self, vocab_size, embed_dim, rnn_hidden_dim):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim)
        self.gru = nn.GRU(embed_dim, rnn_hidden_dim, batch_first=True)
        self.layer_norm = nn.LayerNorm(rnn_hidden_dim)
        self.projection = nn.Linear(rnn_hidden_dim, vocab_size)

    def forward(self, x):
        embedded = self.embedding(x)  # (batch_size, seq_len, embed_dim)
        gru_out, hidden_state = self.gru(embedded)  # (batch_size, seq_len, rnn_hidden_dim), (1, batch_size, rnn_hidden_dim)
        normed = self.layer_norm(gru_out)
        logits = self.projection(normed)  # (batch_size, seq_len, vocab_size)
        return logits, hidden_state

    def stepwise_forward(self, x, prev_hidden_state):
        embedded = self.embedding(x)  # (1, 1, embed_dim)
        gru_out, hidden_state = self.gru(embedded, prev_hidden_state)  # (1, 1, rnn_hidden_dim)
        normed = self.layer_norm(gru_out)
        logits = self.projection(normed)  # (1, 1, vocab_size)
        return logits, hidden_state

model = RecurrentLM(vocab_size=tokenizer.vocab_size, embed_dim=64, rnn_hidden_dim=1024)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)

# Run a forward pass to check model output
X_batch = X[:32]  # Use a batch from the dataset
X_batch = X_batch.to(device)
logits, hidden_state = model(X_batch)

print(f"Shape of logits: {logits.shape}")  # (batch_size, chunk_len, vocab_size)
print(f"Shape of hidden_state: {hidden_state.shape}")

with open(output_file, "a", encoding="utf8") as outfile:
    outfile.write("\nCheckpoint 2.2: \n")
    outfile.write(f"Shape of logits: {logits.shape}\n")  # (batch_size, chunk_len, vocab_size)
    outfile.write(f"Shape of hidden_state: {hidden_state.shape}\n")

# Checkpoint 2.3: Train RecurrentLM
def trainLM(model, dataloader, pad_token_id, learning_rate, device, epochs=15):
    model.to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
    criterion = nn.CrossEntropyLoss(ignore_index=pad_token_id)
    losses = []

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0
        for X_batch, y_batch in dataloader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            optimizer.zero_grad()
            logits, _ = model(X_batch)
            logits = logits.view(-1, logits.size(-1))  # (batch_size * seq_len, vocab_size)
            y_batch = y_batch.view(-1)  # (batch_size * seq_len)
            loss = criterion(logits, y_batch)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()
        avg_loss = epoch_loss / len(dataloader)
        losses.append(avg_loss)
        print(f'Epoch {epoch+1}/{epochs}, Loss: {avg_loss:.4f}')
    return losses

# Initialize and train the model
losses = trainLM(model, dataloader, tokenizer.pad_token_id, learning_rate=0.0007, device=device)

# Plot loss curve
plt.plot(range(1, 16), losses)
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.title('Training Loss Curve')
plt.savefig('loss_curve.pdf')  # Save to PDF

with open(output_file, "a", encoding="utf8") as outfile:
    outfile.write("\nCheckpoint 2.3: \n")
    samples = [
        "And you gotta live with the bad blood now",
        "Sit quiet by my side in the shade",
        "And I'm not even sorry, nights are so starry",
        "You make me crazier, crazier, crazier, oh",
        "When time stood still and I had you"
    ]

    for sample in samples:
        model.eval()
        tokens = tokenizer.encode(sample)
        X = torch.tensor([tokens[:-1]], device=device)
        y = torch.tensor([tokens[1:]], device=device)
        with torch.no_grad():
            logits, _ = model(X)
            probs = F.softmax(logits, dim=-1)
            target_probs = probs.gather(2, y.unsqueeze(2)).squeeze(2)
            mask = y != tokenizer.pad_token_id
            target_probs = target_probs[mask]
            if target_probs.numel() == 0:
                ppl = float('inf')
            else:
                probs_list = target_probs.tolist()
                ppl = get_perplexity(probs_list)

        print(f"Perplexity for '{sample}': {ppl:.4f}")
        outfile.write(f"Perplexity for '{sample}': {ppl:.4f}\n")

# Checkpoint 2.4: Autoregressive Lyric Generation
def generate(model, tokenizer, start_phrase, max_len, device):
    model.eval()
    tokens = tokenizer.encode(start_phrase)
    generated_tokens = tokens.copy()
    hidden_state = None

    with torch.no_grad():
        if len(tokens) > 1:
            X = torch.tensor([tokens[:-1]], device=device)
            logits, hidden_state = model(X)
            next_token = torch.argmax(logits[:, -1, :], dim=-1).item()
            generated_tokens.append(next_token)
        else:
            next_token = tokens[0]

        for _ in range(max_len - len(generated_tokens)):
            X = torch.tensor([[next_token]], device=device)
            logits, hidden_state = model.stepwise_forward(X, hidden_state)
            next_token = torch.argmax(logits, dim=-1).item()
            generated_tokens.append(next_token)
            if next_token in [tokenizer.eos_token_id, tokenizer.pad_token_id]:
                break

    return generated_tokens

with open(output_file, "a", encoding="utf8") as outfile:
    outfile.write("\nCheckpoint 2.4: \n")
    start_phrases = [
        "<s>Are we",
        "<s>Like we're made of starlight, starlight",
        "<s>She shares my dream"
    ]
    for phrase in start_phrases:
        generated_ids = generate(model, tokenizer, phrase, max_len=64, device=device)
        generated_text = tokenizer.decode(generated_ids)
        print(f"Start: {phrase}\nGenerated: {generated_text}\n")
        outfile.write(f"Start: {phrase}\nGenerated: {generated_text}\n\n")

#-------------------------------------------------------------------------------------------

from google.colab import files
files.download("a2_p2_Shah_116727594_OUTPUT.txt")

